### ISSUE TITLE
Compact Badges doesn't work anymore since months now

### ISSUE THREAD

**Issue by SJ-Tom** [cs-jako/LM4-Badges#11]
For months now, I have had the error that Streak 3 and 1 are visible at the same time, but fortunately not 2. Unfortunately this bug has never been fixed, and I hope that this can be fixed soon as I find it strange to see Streak 3 then have Tag Contributor in between and then Streak 1 is still there

**Comment by cs-jako** [comment]
Thank you for the report!
The visual bug with streak badges (still showing 1 when showing 3) has been fixed.

I also added sorting to the Badges (which isn't done by the endpoint from Laby.net) so that for example the Streak Badges are in ascending order.

**Comment by cs-jako** [comment]
Will be fixed within the next release on flintmc and will be auto-updated if you have the addon installed
