### ISSUE TITLE
Badge layered behind signs

### ISSUE THREAD

**Issue by SJ-Tom** [cs-jako/LM4-Badges#6]
I was just walking through my world and accidentally discovered this error. The badges become invisible or covered by signs even if they are several blocks away, as in this case. You can see this very well in the picture.
I hope that can help fixing the bug.

Picture: _https://laby.net/post/WQKpXIjd_

Operating System: Windows 11
LabyMod Version: 4.0.0+710 snapshot/3d12f6db
Minecraft Version: 1.19.4
Addon Version: 1.4.0 - I know that there is version 1.5, but this is not adopted by LabyMod.
Installed Addons: Badges, BetterPerspective, DamageIndicator, Flux, Friend Tags, Full Bright, HDSkins, Spotify, ToggleSneak, VoiceChat

**Comment by SJ-Tom** [comment]
Yesterday I also noticed that the badges also turn blue when there is water behind them.

**Comment by cs-jako** [comment]
That's currently caused by the LabyMod render pipeline. As soon as they updated it I'll make sure to fix this issue.

**Comment by SJ-Tom** [comment]
Thank you for the answer. Then LabyMod will have to fix it.
